sequenceDiagram
    participant MCP Client as MCP Client<br>(VSCode/Autogen)
    participant APIM as APIM +<br>Crendential Manager
    participant MCP Server as MCP Server<br>(Container Apps)
    participant Backend as Backend<br>(Github)

    MCP Client->>APIM: /sse
    APIM->>MCP Server: list tools
    MCP Server->>MCP Client: existing backend tools<br/> + "authorize_github" tool
    MCP Client->>MCP Client: process prompt
    MCP Client->>MCP Server: /authorize_github
    MCP Server->>MCP Server: generate `authorization_id` <br>based on the current session
    MCP Server->>APIM: Check status
    APIM->>MCP Client: connected
    MCP Client->>MCP Server: /get_issues (no token)
    MCP Server->>MCP Server: attach `authorization_id` as request header
    MCP Server->>APIM: /get_issues (no token)
    APIM->>APIM: get token for the `authorization_id`
    APIM->>Backend: /get_issues (with token)
